## About this book
This book is written as a companion book to the [Statistical Inference](https://www.coursera.org/course/statinference)
Coursera class as part of the [Data Science Specialization](https://www.coursera.org/specialization/jhudatascience/1?utm_medium=courseDescripTop). However, if you do not take the class, the book mostly stands on its own. A
useful component of the book is a series of YouTube videos that comprise the
Coursera class.

The book is intended to be a low cost introduction to the important field of
statistical inference. The intended audience are students who are numerically
and computationally literate, who would like to put those skills to use in
Data Science or Statistics. The book is offered for free as a series of
markdown documents on github and in more convenient forms (epub, mobi) on
LeanPub and retail outlets.

This book is licensed under a
[Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/),
which requires author attribution for derivative works, non-commercial use of derivative
works and that changes are shared in the same way as the original work.


## About the picture on the cover
The picture on the cover is a public domain image taken from Wikipedia's
article on Francis Galton's quincunx. Francis Galton was an 19th century
polymath who invented many of key concepts of statistics. The quincunx
was an ingenious invention for illustrating the central limit theorem
using a pinball setup.
